server:
  port: ${PORT:7502}
  servlet:
    context-path: /param

spring:
  application:
    name: params-service
  datasource:
    url: jdbc:h2:mem:param
    driver-class-name: org.h2.Driver
    username: param
    password: param
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: false
  logging:
    pattern:
      console: "%clr(%d{yyyy-MM-dd HH:mm:ss}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([${springAppName:-},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-}]){yellow} %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}"
    level:
      org.springframework: WARN
      org.hibernate: WARN
  logstash:
    server: logstash
    port: 5000
  zipkin:
    base-url: ${ZIPKIN_URL:http://zipkin:9411}/    

management:
  endpoints:
    web:
      exposure:
        include: "*"

  metrics:
    distribution:
      percentiles-histogram.http.server.requests: false
      percentiles.http.server.requests: 0.5, 0.9, 0.95, 0.99, 0.999
      sla.http.server.requests: 500ms, 2000ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://discovery:8761}/eureka/

id-request-key: X-Global-Transaction-ID
service-base-url: /api/

springdoc:
  swagger-ui:
    disable-swagger-default-url: true